i18n_language: zh-hans
downloader:
  genome_sources_file: genome_sources_list.yml
  download_output_base_dir: downloaded_cotton_data
  force_download: false
  max_workers: 3
  proxies:
    http: http://127.0.0.1:7890
    https: http://127.0.0.1:7890
integration_pipeline:
  input_excel_path: path/to/your/input_data.xlsx
  bsa_sheet_name: BSA_Results
  hvg_sheet_name: HVG_List
  output_sheet_name: Combined_BSA_HVG_Analysis
  bsa_assembly_id: NBI_v1.1
  hvg_assembly_id: HAU_v2.0
  gff_files:
    NBI_v1.1: null
    HAU_v2.0: null
  homology_files:
    bsa_to_bridge_csv: null
    bridge_to_hvg_csv: null
  bridge_species_name: Arabidopsis_thaliana
  gff_db_storage_dir: gff_databases_cache
  force_gff_db_creation: false
  bsa_columns:
    chr: chr
    start: region.start
    end: region.end
  hvg_columns:
    gene_id: gene_id
    category: hvg_category
    log2fc: log2fc_WT_vs_Ms1
  homology_columns:
    query: Query
    match: Match
    evalue: Exp
    score: Score
    pid: PID
  selection_criteria_source_to_bridge:
    sort_by:
    - Score
    - Exp
    ascending:
    - false
    - true
    top_n: 1
    evalue_threshold: 1.0e-10
    pid_threshold: 30.0
    score_threshold: 50.0
  selection_criteria_bridge_to_target:
    sort_by:
    - Score
    - PID
    ascending:
    - false
    - false
    top_n: 1
    evalue_threshold: 1.0e-15
    pid_threshold: 40.0
    score_threshold: 80.0
  common_hvg_log2fc_threshold: 1.0
_config_file_abs_path_: D:\Python\cotton_tool\config.yml
